project:
  type: website
  output-dir: docs
  resources:
    - _shared/

website:
  title: "R Lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ggplot-gallery/index.qmd
        text: ggplot Gallery

execute:
  warning: false
  message: false
  eval: true
  echo: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show solution"
    css: "/_shared/styles.css"