project:
  type: website
  output-dir: docs

website:
  title: "R Lectures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ggplot-gallery/index.qmd
        text: ggplot Gallery

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show solution"
    css: _shared/styles.css