project:
  type: website
  output-dir: docs
  render:
    - "src/**/*.qmd"

website:
  title: "R Lectures"
  navbar:
    left:
      - href: src/index.qmd
        text: Home
      - href: src/ggplot-gallery/index.qmd
        text: ggplot Gallery
    right:
      - icon: github
        href: https://github.com/jana-dlouha/r-lectures

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show solution"
    code-tools: true
    css: src/_shared/styles.css
    link-external-newwindow: true